# Shared research-report conventions, intentionally dependency-light.
suppressPackageStartupMessages(library(ggplot2))
theme_set(theme_minimal(base_size = 14) +
  theme(plot.title = element_text(face = "bold", color = "#142d42"),
        plot.subtitle = element_text(color = "#687b89"),
        panel.grid.minor = element_blank(), legend.position = "top",
        plot.background = element_rect(fill = "white", color = NA)))
xml_escape <- function(x) {
  x <- gsub("&", "&amp;", x, fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  gsub(">", "&gt;", x, fixed = TRUE)
}
publish_plot <- function(plot, path, title, description, width = 10, height = 6) {
  dir.create(dirname(path), showWarnings = FALSE, recursive = TRUE)
  plot <- plot + theme(plot.title = element_text(face = "bold", color = "#142d42"),
                       plot.subtitle = element_text(color = "#687b89"),
                       plot.margin = margin(12, 16, 12, 12))
  ggsave(path, plot, device = svglite::svglite, width = width, height = height, bg = "white")
  svg <- paste(readLines(path, warn = FALSE), collapse = "\n")
  svg <- sub("<svg ", '<svg role="img" aria-labelledby="title desc" ', svg, fixed = TRUE)
  svg <- sub("(<svg[^>]*>)", paste0("\\1<title id=\"title\">", xml_escape(title),
        "</title><desc id=\"desc\">", xml_escape(description), "</desc>"), svg, perl = TRUE)
  writeLines(svg, path, useBytes = TRUE)
}
md_table <- function(data, digits = 3) {
  data <- as.data.frame(data)
  for (name in names(data)) {
    missing <- is.na(data[[name]])
    if (is.numeric(data[[name]])) data[[name]] <- format(round(data[[name]], digits), trim = TRUE, scientific = FALSE)
    data[[name]] <- gsub("|", "/", as.character(data[[name]]), fixed = TRUE)
    data[[name]][missing] <- "Not reported"
  }
  c(paste0("| ", paste(names(data), collapse = " | "), " |"),
    paste0("| ", paste(rep("---", ncol(data)), collapse = " | "), " |"),
    apply(data, 1, function(row) paste0("| ", paste(row, collapse = " | "), " |")))
}
write_research_report <- function(lines) {
  dir.create("outputs", showWarnings = FALSE)
  writeLines(c(lines, "", "## Reproduction", "",
    "This report and its figures are generated by the repository scripts from deterministic synthetic data.",
    "See the repository README for commands and the versioned environment.",
    "", "[Runtime session and package versions](session-info.txt)"), "outputs/report.md", useBytes = TRUE)
  writeLines(capture.output(sessionInfo()), "outputs/session-info.txt", useBytes = TRUE)
}
